# Generated by Django 5.1.1 on 2024-11-06 11:01

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_usersdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_File_Name),
        ),
    ]
