# Generated by Django 5.1.1 on 2024-11-06 13:38

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.get_File_Name),
        ),
    ]
