# Generated by Django 5.1.1 on 2024-11-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersDetails',
        ),
    ]
