# Generated by Django 5.1.1 on 2024-11-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product_qty',
        ),
    ]
