# Generated by Django 5.1.5 on 2025-01-30 14:53

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userid',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userid',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=user.models.get_file_name),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vender', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to=user.models.get_file_name)),
                ('descriptions', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('emi', models.BooleanField(default=False, help_text='0-noEMI, 1-EMI')),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-hidden')),
                ('treading', models.BooleanField(default=False, help_text='0-default, 1-treading')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
