# Generated by Django 5.1.5 on 2025-01-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userid_pin_userid_state_userid_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='town',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField()),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userid')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userid')),
            ],
        ),
    ]
