# Generated by Django 5.1.5 on 2025-01-31 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, help_text='0-False, 1-True')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userid')),
            ],
        ),
    ]
