# Generated by Django 5.1.5 on 2025-02-01 15:12

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to=user.models.get_file_name),
        ),
    ]
