# Generated by Django 5.1.5 on 2025-02-03 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_address_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='card_pin',
            field=models.IntegerField(default=1111, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='card',
            field=models.IntegerField(default=1111, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
