# Generated by Django 5.1.5 on 2025-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery',
            field=models.BooleanField(default=False, help_text='0-NotDelivery, 1-Delivery'),
        ),
    ]
